'number' + 3 + 3 //('number33' concatenation)
null + 3 //(3, math operation,nothing (0) plus 3)
5 && "qwerty" //('qwerty', 5 returns true so && returns second part)
+'40' + +'2' + "hillel" //('42hillel', string to number,math,concatination)
'10' - 5 === 6 //(false, math, then 5 is not equal 6)
true + false //(1, math operation true - 1, false - 0)
'4px' - 3 //(NaN, math operation, can not convert string to proper number)
'4' - 3 //(1, math operation, string can be converted to number)
'6' + 3 ** 0 //(61, first math 3 ** 0 = 1, and then concatination)
12 / '6' //(2, math operation string was converted to number)
'10' + (5 === 6) //('10false', 5 not equal 6 = false, then concatination)
null == '' //(false, null doesn't equal to empty string)
3 ** (9 / 3) //(27, 9/3 = 3, 3 ** 3 = 27)
!!'false' == !!'true' //(true, string value is true, !! - convert to the same boolean value, true == true)
0 || '0' && 1 //(1, first logical AND returns 1, then logical OR returns 0 || 1 = 1)
(+null == false) < 1 //(false, null converted to 0, false converted to 0, so result in () is true, true converted to 1, 1<1 - false)
false && true || true //(true, logical AND returns false, then logical OR returns true)
false && (false || true) //(false, logical OR returns true, logical AND returns false)
(+null == false) < 1 ** 5 // (false, null converted to zero, false = 0,  comparison without data type will be true, 1**5=1, true converted to 1, 1<1 - false)